### PR TITLE
Use middleman s3 sync so as to only upload the changed files to s3.

### PR DESCRIPTION
**Pull request by varshavaradarajan**
@arvindsv , Not sure what to do in case of bump_version. Please merge later.

### CODE REVIEW

**Comment by ketan** [comment]
How is /current being handled?

**Comment by varshavaradarajan** [comment]
@ketan , its not. https://github.com/gocd/api.go.cd/pull/163#issue-205109934.  Need to talk to @arvindsv . May be have it as a separate command to upload specific files?

**Comment by ketan** [comment]
Can we punt on this for a few more days? I think I have some ideas, but will talk to you once I'm back.

**Comment by ketan** [comment]
Closing in favor of a custom task that'll upload everything in one go using some differential algorithm.

**Pull request closed without merging**
