### PR TITLE
Fixed authentication example snippet to have correct API version.

### LINKED ISSUE #178: Error in authentication example
I was not able to get the example GoCD authentication code to work using a recent version of GoCD.  It specifies the following CURL command which will return a 404:

image

https://api.gocd.org/current/#basic-authentication

After digging around for awhile I found this under the agents saying the minimum JSON API version should be 4 for /go/api/agents:

image

After changing the accept header to `application/vnd.go.cd.v4+json`, the requests works fine.  I'm not sure if there is something I'm missing here or if this is just an omission.

### PR DESCRIPTION
**Pull request by aaronsaderholm**
The previous example would not work with current verions of GoCD.  resolve #178

### CODE REVIEW

**Comment by ketan** [comment]
@asaderholm — I believe you may be on an older version of GoCD. I'm able to make that request just fine with version v4 of the api. Can you confirm what version of GoCD you're on, and check what the API docs say for that version (use the drop down on the api docs website to select your gocd version)

v4 of the api was introduced in release 16.10 - https://www.gocd.org/releases/#16.10.0

v2 and v3 of the API has been deprecated and removed as of 17.1 - https://www.gocd.org/releases/#17.1.0

**Comment by GaneshSPatil** [comment]
@asaderholm -- ignore Ketan's comment about the version mismatch, It was a confusion between the `authentication example` and `agents API` example.

can you sign the CLA please? I will merge this PR.

**Comment by GaneshSPatil** [comment]
@asaderholm -- you also need to make an API version change [here](https://github.com/gocd/api.go.cd/blame/master/source/includes/_020-authentication.md#L20)

**Comment by asaderholm** [comment]
I signed the CLA before doing the pull request.  

I updated it but I'm just guessing it comes back as v4:
```Content-Type: application/vnd.go.cd.v4+json; charset=utf-8```

I can't readily confirm from where I'm sitting at the moment.  I'll try and check on that and post back in a few days.

**Comment by varshavaradarajan** [comment]
@aaronsaderholm - thanks for the PR. We made a  change in the example we used for authentication some time ago. So, closing this PR.

**Pull request closed without merging**
